# Generated by Django 5.0.7 on 2025-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_voter_is_staff_voter_is_superuser_alter_voter_scc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
